TARGET_CLASSES:
- 0
- 1
- 1
- 1
CONF: 0.1
IOU: 0.0
DELAY: 0.0
VORSCHUSS: 0
NACHSCHUSS: 0
BEISCHUSS: 0
THRESHOLD: 300.0
VERT_MOVEMENT: 0
CALIBRATED_VERT_MOVEMENT: 40.0
RUN_VERT_CALIBRATION: false
RECORD_RAW: false
DRAW_BBOXES: true
ROTATE: 1
FLIP_H: false
FLIP_V: false
RAW_RECORDING_FPS: 2.0
GUI_RECORDING_FPS: 2.0
FPS: 30
RAW_RECORDING_DIR: C:\Users\GKoinig\Desktop\SenSoRTC-development\SenSoRTC-development\NIR_RECORDINGS
GUI_RECORDING_DIR: Recordings_GUI
NIR_CLASS_COLORS:
- - 0
  - 0
  - 0
- - 255
  - 64
  - 64
- - 64
  - 220
  - 64
- - 64
  - 128
  - 255
